---
- name: Preparatory Stage Before Installing K8S
  gather_facts: yes
  hosts: all
  become: true
 
  vars_prompt:
  - name: reboot_question
    prompt: "Reboot Hosts Systems for Disable Selinux? (yes/no) (default=no)"
    private: no
  tasks:
  - name: Configure modprobe br_netfilter=true
    modprobe:  name="br_netfilter" state=present
  - name: add config file /etc/modules-load.d/k8s.conf and /etc/sysctl.d/k8s.conf
    ansible.builtin.lineinfile:
      path: /etc/modules-load.d/k8s.conf
      line: br_netfilter
      create: yes
  - name: add config file and /etc/sysctl.d/k8s.conf
    ansible.builtin.lineinfile:
      create: yes
      path: /etc/sysctl.d/k8s.conf
      line: '{{ item }}'
    with_items:
      - 'net.bridge.bridge-nf-call-ip6tables = 1'
      - 'net.bridge.bridge-nf-call-iptables = 1'
  - name: Enable ipv4.ip_forward
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

  - name: Build hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_default_ipv4.address }} {{item}}'
      state: present
    with_items: '{{ groups["all"] }}'

  - name: Disable Selinux
    selinux:
      state: disabled

  - name: Configure /etc/docker/daemon.json and restart docker.service
    ansible.builtin.lineinfile:
      create: yes
      path: /etc/docker/daemon.json
      line: '{{ item }}'
    with_items:
      - '{"exec-opts": ["native.cgroupdriver=systemd"],'
      - '"log-driver": "json-file",'
      - '"log-opts": {"max-size": "100m"},'
      - '"storage-driver": "overlay2"}'
    notify: Restart Docker Service
  
  - name: Reboot all hosts of inventory now To apply selinux changes?
    reboot:
    async: 1
    poll: 0
    when: reboot_question == "yes"
 
  handlers:
  #этот хендлер запустится когда будет таска с  "notify: Restart Docker Service"
  - name: Restart Docker Service
    service: name=docker state=restarted

