---
- name: Install Docker
  gather_facts: yes
  hosts: all
  become: true
  
  tasks:
  - name: Configure modprobe br_netfilter=true
    modprobe:  name="br_netfilter" state=present
  - name: add config file /etc/modules-load.d/k8s.conf and /etc/sysctl.d/k8s.conf
    ansible.builtin.lineinfile:
      path: /etc/modules-load.d/k8s.conf
      line: br_netfilter
      create: yes
  - name: add config file and /etc/sysctl.d/k8s.conf
    ansible.builtin.lineinfile:
      create: yes
      path: /etc/sysctl.d/k8s.conf
      line: '{{ item }}'
    with_items:
      - 'net.bridge.bridge-nf-call-ip6tables = 1'
      - 'net.bridge.bridge-nf-call-iptables = 1'
  - name: Enable ipv4.ip_forward
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

  - name: Build hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_default_ipv4.address }} {{item}}'
      state: present
    with_items: '{{ groups["all"] }}'
