---
- hosts: all
  tasks:
  - name: ADD /root/.ssh/id_rsa.pub file in authorized_key
    authorized_key:
# ключи добавятся пользователю root ...
      user: root
      state: present
# ... из нашего файла root.pub
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    tags:
      - add-ssh-keys
